# link for tutorial I got all the files in frontend from:
# https://medium.com/@pavan168/pavanwelihinda-running-react-native-in-docker-a0fe0b0c776e

version: "3.5"

services:
    expo_android:
        container_name: expo_android
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        ports:
            - 19000:19000
            - 19001:19001
        volumes:
            - ${PWD}/:/app/
