version: '3.7'

services:
    bitfit:
        build:
            context: .
            dockerfile: Dockerfile
        command: python runner.py run -h 0.0.0.0
        ports:
            - 4200:5000
        env_file:
            - ./.env.dev
        volumes:
            - '.:/usr/src/app'
        container_name: bitfit