version: '3.7'

services:
    bitfit:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: bitfit
        command: python runner.py run -h 0.0.0.0
        env_file: ./.env.dev
        ports: 
            - 4200:5000
        volumes: 
            - '.:/usr/src/app'
